
services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    env_file:
      - .env

  scheduler:
    build: ./scheduler
    depends_on:
      - mongo
      - rabbitMQ
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      RABBITMQ_HOST: "rabbitMQ"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      PYTHONUNBUFFERED: "1"

  rabbitMQ:
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASS}

  worker:
    build: ./worker
    depends_on:
      - rabbitMQ
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      RABBITMQ_HOST: "rabbitMQ"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      PYTHONUNBUFFERED: "1"
volumes:
  mongo-data:

networks:
  app-net:
